sudo: required

language: bash

services:
  - docker

before_script:
  - echo $TRAVIS_TAG > VERSION
  - docker -v
  - docker-compose -v
  - docker-compose build


after_success:
  - docker images

after_error:
  - docker-compose logs

after_failure:
  - docker-compose logs

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
