imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: true }

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

monolog:
    handlers:
        file_log:
            ident: %app_name%
            type: stream
            level: debug
            bubble: false
            path: php://stdout

assetic:
    use_controller: "%use_assetic_controller%"

#swiftmailer:
#    delivery_address: me@example.com
