imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        syslog:
            ident: %app_name%
            type: stream
            level: debug
            bubble: false
            path: ../symfony-%app_name%.log
