keboola_jsonparser_api_index:
    path:     /
    defaults: { _controller: KeboolaJsonparserApiBundle:Default:index }
    requirements:
        _method:  GET

keboola_jsonparser_api_convert:
    path:     /convert
    defaults: { _controller: KeboolaJsonparserApiBundle:Api:get }
    requirements:
        _method:  GET

keboola_jsonparser_api_convert_line_delimited:
    path:     /convert
    defaults: { _controller: KeboolaJsonparserApiBundle:Api:post }
    requirements:
        _method:  POST

keboola_health_check:
    path: /health-check
    defaults: { _controller: KeboolaJsonparserApiBundle:Api:health }
    requirements:
      _method: GET
